### PR TITLE
Move loopbackExempt into windowslib

### PR DESCRIPTION
**Pull request by sgtcoolguy**
- Make wstool return pid after launching app.
- Move common code to utilities for checking if wptool/wstool need to be rebuilt.
- Add method for loopback exempting a Windows Store app by id/Name.
- Add a unit test for winstore.getAppxPackages()
- Fix broken wp_get_appx_metadata.ps1 file from newline mid-line

### CODE REVIEW

**Comment by infosia** [comment]
```
$npm run-script test-device
...
  1) device detect Windows Phone devices:
     Uncaught AssertionError: expected Object {
  index: 0,
  ip: '127.0.0.1',
  name: 'Windows 10 Mobile Device',
  udid: '00000015-c47f-8a24-0000-000000000000',
  wpsdk: null
} to have keys name, udid, index, wpsdk
        extra keys: ip
```

^^ because `should(dev).have.keys('name', 'udid', 'index', 'wpsdk')` compares *exact* keys in the object.

```
$ npm run-script test-winstore
  winstore
    √ namespace should be an object
    - launch should launch Windows Store App
    1) getAppxPackages should have preset Windows packages
    √ detect should find Windows Store SDK installations

  2 passing (1s)
  1 pending
  1 failing

  1) winstore getAppxPackages should have preset Windows packages:
     Uncaught AssertionError: expected Object {
  Architecture: 'X86',
  Dependencies: '{Microsoft.VCLibs.140.00.Debug_14.0.23506.0_x86__8wekyb3d8bbwe,',
  IsBundle: 'False',
  IsDevelopmentMode: 'True',
  IsFramework: 'False',
  IsResourcePackage: 'False',
  Name: '43a63748-23c7-4702-bb77-7ac4fb103559',
  PackageFamilyName: '43a63748-23c7-4702-bb77-7ac4fb103559_8wekyb3d8bbwe',
  PackageFullName: '43a63748-23c7-4702-bb77-7ac4fb103559_1.0.0.0_x86_NorthAmerica_8wekyb3d8bbwe',
  Publisher: 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US',
  PublisherId: '8wekyb3d8bbwe',
  ResourceId: 'NorthAmerica',
  Version: '1.0.0.0'
} to have property InstallLocation
      at windowslib\test\test-winstore.js:48:34
      at Array.forEach (native)
      at windowslib\test\test-winstore.js:47:26
      at windowslib\lib\winstore.js:142:3
```

**Comment by infosia** [comment]
Hmm. For me I see some `Dependencies` ends with `...`. I'm not sure why.

```
  1) winstore getAppxPackages should have preset Windows packages:

      Uncaught AssertionError: expected '{Microsoft.VCLibs.140.00_14.0.22929.0_x64__8wekyb3d8bbwe,Microsoft.NET.Native.Runtime.1.1_1.1.23406.0_x64__8wekyb3d8bbwe,Microsoft.Windows.Photos_16.201.11370.0_neutral_split.scale-150_8wekyb3d8bbwe,Microsoft.Windows.Photos_16.201.11370.0_neutral_split.scale-100_8wekyb3d8bbwe...}' to be '{Microsoft.VCLibs.140.00_14.0.22929.0_x64__8wekyb3d8bbwe,Microsoft.NET.Native.Runtime.1.1_1.1.23406.0_x64__8wekyb3d8bbwe,Microsoft.Windows.Photos_16.201.11370.0_neutral_split.scale-100_8wekyb3d8bbwe,Microsoft.Windows.Photos_16.201.11370.0_neutral_split.scale-150_8wekyb3d8bbwe}'
      + expected - actual

      -{Microsoft.VCLibs.140.00_14.0.22929.0_x64__8wekyb3d8bbwe,Microsoft.NET.Native.Runtime.1.1_1.1.23406.0_x64__8wekyb3d8bbwe,Microsoft.Windows.Photos_16.201.11370.0_neutral_split.scale-150_8wekyb3d8bbwe,Microsoft.Windows.Photos_16.201.11370.0_neutral_split.scale-100_8wekyb3d8bbwe...}
      +{Microsoft.VCLibs.140.00_14.0.22929.0_x64__8wekyb3d8bbwe,Microsoft.NET.Native.Runtime.1.1_1.1.23406.0_x64__8wekyb3d8bbwe,Microsoft.Windows.Photos_16.201.11370.0_neutral_split.scale-100_8wekyb3d8bbwe,Microsoft.Windows.Photos_16.201.11370.0_neutral_split.scale-150_8wekyb3d8bbwe}

      at Assertion.fail (windowslib\node_modules\should\lib\assertion.js:180:17)
      at Assertion.prop.value (windowslib\node_modules\should\lib\assertion.js:65:17)
      at windowslib\test\test-winstore.js:76:62
```

**Comment by sgtcoolguy** [comment]
Hmm, the ordering of the dependencies is also different for you and me (the scale-100 vs scale-150). I may need to just make sure it contains specific substrings rather than an exact full match. (or actually turn the dependencies value into an array of strings?)

**Comment by sgtcoolguy** [comment]
Manually merged after fixing up unit test.

**Pull request merged**
